-- Fix the smokeusage.id column to be an auto-incrementing identity
-- First drop the existing column
ALTER TABLE public.smokeusage DROP COLUMN id;

-- Add a new auto-incrementing identity column
ALTER TABLE public.smokeusage ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;